spring:
  application:
    name: Bibi
  aop:
    proxy-target-class: true
  social:
    facebook:
      app-id: 331963721001732
      app-secret: 36884a5bf449aa541a590945784c0755
server:
  port: 8080

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

eureka:
  instance:
    hostname: localhost
    port: 8000
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

zuul:
#(prefix: /api doesn't work with the other apis context-paths)
  routes:
    auto:
      path: /auto/**
      serviceId: lyne
      stripPrefix: false
      sensitiveHeaders:
    auth:
      path: /auth/**
      serviceId: mima
      stripPrefix: false
      sensitiveHeaders:

security:
  basic:
    enabled: false
  oauth2:
    client:
      clientId: CLIENT_APP
      clientSecret: password
      accessTokenUri: http://localhost:9000/auth/oauth/token
      userAuthorizationUri: http://localhost:9000/auth/oauth/authorize
    resource:
      token-type: Bearer
      client:
      id: CLIENT_RESOURCE
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzKOkPFC8hoRExHRtkXUK
          qI1jKU1T0Dr+ReoD6F76w2ZqcvFgqGOOUa+zmXiHCVRNGFVLpIkWYUaulY0r3Nf1
          9hRbISu/jn51D4cJcIgldlY99QT3oEH9w1M1y8WvFL8wufIaPcn8w05EVLrKtkfO
          wCb45jwbsW2/QcTQXmSXUV6tD+38DEIUDSAyahw1Vd2ZiPLyhHsQQzCQP5uQ+rur
          2qnPz3qBpWn0aNsA+xCtyeMr8VIss+uo1BFE3BEzBT6N7nvGxLCYrLGDzO3JQIY1
          XtDw668XgC/Ft/9WmxpC72txfceocep95L5cd1eKTSwA0fhQJfD3P4PEMtmqzK7E
          iwIDAQAB
          -----END PUBLIC KEY-----

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

ribbon:
  ConnectTimeout: 5000
  ReadTimeout: 5000
